# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569cf47d7069a19e22b3bdba4645c5dc973421bf6510713fe1aab2900ab1b3f4122d16fbd4f64f675be3d574ef30ba9cca0c7018130798a99f1b4ef107526f71

test:
  secret_key_base: dc8700a2dc75c79e0bbc536b6a81f62b051b27925ad87ac5895b45d36934a99e655ee9e17e5ebf0057a79cb1d92e57a18980922b2eada08004b62124706597b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
